name: test condition
on: [push]


jobs:
  say-hello:
    env:
      VAR_2: from job
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo ${{ 42 }}

      - id: env
        run: |
          echo $GITHUB_OUTPUTS
          echo FROM_ENV=value_step >> $GITHUB_OUTPUT

      - id: test
        run: |
          echo ${{ 'main' == 'top' }}
          echo test : $FROM_ENV
          echo ${{ steps.env.outputs.FROM_ENV }}

      - run: echo ${{ contains(github.ref, 'main') }}

      - run: exit 1

      - run: echo STEP 2
        if: always()

  deploy:
    needs: say-hello
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy in prod
