name: Second workflow
on: [push]

env:
  VAR_1: from workflow

jobs:
  say-hello:
    env:
      VAR_2: from job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: echo file
        run: ls
        env:
          VAR_3: from step
      - name: use env
        run: |
          echo VAR_1: $VAR_1
          echo VAR_2: $VAR_2
          echo VAR_3: $VAR_3
          echo VAR_REPO: $VAR_REPO
          echo SECRET: $SECRET_1
