name: test condition
on: [push]


jobs:
  say-hello:
    env:
      VAR_2: from job
    runs-on: ubuntu-latest
    outputs:
      FROM_SAY: ${{ steps.env.outputs.FROM_ENV }}
    steps:
      - id: step1
        run: echo ${{ 42 }}

      - id: env
        run: |
          echo $GITHUB_OUTPUTS
          echo FROM_ENV=value_step >> $GITHUB_OUTPUT

      - id: test
        run: |
          echo ${{ 'main' == 'top' }}
          echo ne marche pas : $FROM_ENV
          echo ${{ steps.env.outputs.FROM_ENV }}


  deploy:
    needs: say-hello
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.say-hello.outputs.FROM_SAY }}
