name: test condition
on: [push]


jobs:
  say-hello:
    env:
      VAR_2: from job
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ 42 }}
      - run: echo ${{ 'main' == 'top' }}
      - run: echo ${{ contains(github.ref, 'main') }}
      - run: exit 1
      - run: echo STEP 2
        if: always()
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy in prod
